# Generated by Django 6.0.3 on 2026-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiments',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
