# Generated by Django 6.0.3 on 2026-03-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0002_review_sentiments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='crete_at',
            new_name='created_at',
        ),
    ]
