# Generated by Django 6.0.3 on 2026-03-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0003_rename_crete_at_review_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sentiments',
            new_name='sentiment',
        ),
    ]
