# Generated by Django 6.0.3 on 2026-03-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0004_rename_sentiments_review_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sentiment',
            new_name='sentiments',
        ),
    ]
